#+TITLE: Doom Emacs Configuration
#+AUTHOR: dzhma
#+PROPERTY: header-args:emacs-lisp :tangle config.el
#+auto_tangle: t
#+STARTUP: showeverything

* General Configuration
Place your private configuration here! Remember, you do not need to run 'doom
sync' after modifying this file!

Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates, and snippets. It is optional.

#+BEGIN_SRC emacs-lisp
;; (setq user-full-name "John Doe"
;;       user-mail-address "john@doe.com")
#+END_SRC


* Font Configuration
Doom exposes five (optional) variables for controlling fonts in Doom:
- ~'doom-font~ -- the primary font to use
- ~'doom-variable-pitch-font~ -- a non-monospace font (where applicable)
- ~'doom-big-font~ -- used for ~`doom-big-font-mode~; use this for
  presentations or streaming.
- ~'doom-symbol-font~ -- for symbols
- ~'doom-serif-font~ -- for the ~fixed-pitch-serif~ face

  #+BEGIN_SRC emacs-lisp :tangle yes
(setq doom-font (font-spec :family "Input Mono" :size 16))
  #+END_SRC


* Theme Configuration
There are two ways to load a theme. Both assume the theme is installed and
available. You can either set ~doom-theme~ or manually load a theme with the
~load-theme~ function. This is the default:

#+BEGIN_SRC emacs-lisp :tangle yes
(setq doom-theme 'doom-lantern)
#+END_SRC


* Line Number Style
This determines the style of line numbers in effect. If set to ~`nil~, line
numbers are disabled. For relative line numbers, set this to ~`relative~.

#+BEGIN_SRC emacs-lisp :tangle yes
(display-line-numbers-mode 1)
(setq display-line-numbers-type 'relative)

(set-face-attribute 'line-number nil :foreground "#00FFFF" :weight 'bold)
(set-face-attribute 'line-number-current-line nil :foreground "#000000" :background "#00FFFF" :weight 'bold)

;; keep the cursor centered to avoid sudden scroll jumps
(require 'centered-cursor-mode)

;; disable in terminal modes
;; http://stackoverflow.com/a/6849467/519736
;; also disable in Info mode, because it breaks going back with the backspace key
(define-global-minor-mode my-global-centered-cursor-mode centered-cursor-mode
  (lambda ()
    (when (not (memq major-mode
                     (list 'Info-mode 'term-mode 'eshell-mode 'shell-mode 'erc-mode)))
      (centered-cursor-mode))))
(my-global-centered-cursor-mode 1)
#+END_SRC


* Org Mode Directory
If you use org and don't want your org files in the default location below,
change ~org-directory~. It must be set before org loads!

#+BEGIN_SRC emacs-lisp :tangle yes
(setq org-directory "~/org/")
#+END_SRC


* Org Mode Customization
Whenever you reconfigure a package, make sure to wrap your config in an
~after!~ block, otherwise Doom's defaults may override your settings.

#+BEGIN_SRC emacs-lisp :tangle yes
(require 'org-modern)
(add-hook 'org-mode-hook #'org-modern-mode)

(require 'vertico-posframe)
(vertico-posframe-mode 1)

(use-package! websocket
  :after org-roam)

(use-package! org-roam-ui
  :after org-roam
  :config
  (setq org-roam-ui-sync-theme t
        org-roam-ui-follow t
        org-roam-ui-update-on-save t
        org-roam-ui-open-on-start t))

(defun my/org-babel-tangle-on-save ()
  (when (eq major-mode 'org-mode)
    (org-babel-tangle)))

(add-hook 'after-save-hook #'my/org-babel-tangle-on-save)

;;(if (require 'toc-org nil t)
;;    (progn
;;      (add-hook 'org-mode-hook 'toc-org-mode)
;;
;;      ;; enable in markdown, too
;;      (add-hook 'markdown-mode-hook 'toc-org-mode)
;;      (define-key markdown-mode-map (kbd "\C-c\C-o") 'toc-org-markdown-follow-thing-at-point))
;;  (warn "toc-org not found"))
#+END_SRC


* Customize Org Mode Heading Sizes
Customize Org Mode heading sizes without changing colors.

#+BEGIN_SRC emacs-lisp :tangle yes
(dolist (face '((org-level-1 . 2.0)
                (org-level-2 . 1.8)
                (org-level-3 . 1.5)
                (org-level-4 . 1.3)
                (org-level-5 . 1.2)
                (org-level-6 . 1.1)
                (org-level-7 . 1.1)
                (org-level-8 . 1.1)))
  (set-face-attribute (car face) nil :height (cdr face)))
#+END_SRC


* Dashboard Configuration
Customize the dashboard and other display settings.

#+BEGIN_SRC emacs-lisp :tangle yes
(setq +doom-dashboard-ascii-banner-fn t)
(display-battery-mode 1)  ;; Enable battery display in the mode line
(display-time-mode 1)  ;; Enable time display in the mode line
(setq display-time-format "%H:%M")  ;; ISO 8601 format
(setq display-time-default-load-average nil)  ;; Hide load average
#+END_SRC


* Customize Org Mode Faces
Set custom colors for Org mode properties.

#+BEGIN_SRC emacs-lisp :tangle yes
(set-face-attribute 'org-level-1 nil :foreground "#00FFFF" :background "#004C4C" :weight 'bold)  ;; Cyan dominant
(set-face-attribute 'org-level-2 nil :foreground "#FFFF00" :background "#5B5B00" :weight 'bold)  ;; Yellow dominant
(set-face-attribute 'org-level-3 nil :foreground "#00FF00" :background "#1F4F16" :weight 'bold)  ;; Green dominant
(set-face-attribute 'org-level-4 nil :foreground "#FFD700" :background "#5B4A08" :weight 'bold)  ;; Yellow gold
(set-face-attribute 'org-level-5 nil :foreground "#40E0D0" :background "#065465" :weight 'bold)  ;; Turquoise
(set-face-attribute 'org-level-6 nil :foreground "#FF0000" :background "#52170B" :weight 'bold)  ;; Red dominant

(set-face-attribute 'org-list-dt nil :foreground "#00FFFF" :background "#004C4C" :weight 'bold)  ;; Light cyan
(set-face-attribute 'org-table nil :foreground "#00FF00" :weight 'bold)                          ;; Green
#+END_SRC


* Customize Markdown Faces
Set custom colors for Markdown properties.

#+begin_src emacs-lisp :tangle yes
(set-face-attribute 'markdown-header-face-1 nil :foreground "#00FFFF" :background "#004C4C" :weight 'bold)  ;; Cyan dominant
(set-face-attribute 'markdown-header-face-2 nil :foreground "#FFFF00" :background "#5B5B00" :weight 'bold)  ;; Yellow dominant
(set-face-attribute 'markdown-header-face-3 nil :foreground "#00FF00" :background "#1F4F16" :weight 'bold)  ;; Green dominant
(set-face-attribute 'markdown-header-face-4 nil :foreground "#FFD700" :background "#5B4A08" :weight 'bold)  ;; Yellow gold
(set-face-attribute 'markdown-header-face-5 nil :foreground "#40E0D0" :background "#065465" :weight 'bold)  ;; Turquoise
(set-face-attribute 'markdown-header-face-6 nil :foreground "#FF0000" :background "#52170B" :weight 'bold)  ;; Red dominant

(set-face-attribute 'markdown-bold-face nil :foreground "#00FFFF" :weight 'bold)
(set-face-attribute 'markdown-italic-face nil :foreground "#00FF00" :weight 'bold)
#+end_src


* Perspective Configuration
Customize the behavior of the Emacs client.

#+BEGIN_SRC emacs-lisp :tangle yes
(setq persp-emacsclient-init-frame-behaviour-override "main")
#+END_SRC


* PDF Opening Functionality
Function to open PDFs with Zathura.

#+BEGIN_SRC emacs-lisp :tangle yes
(defun open-pdf-with-zathura (file)
  "Open the specified PDF file with Zathura."
  (start-process "zathura" nil "zathura" file))

(add-to-list 'auto-mode-alist '("\\.pdf\\'" . default))
(setq dired-guess-shell-alist-user
      '(("\\.pdf\\'" "zathura")))

(add-hook 'find-file-hook
          (lambda ()
            (when (string-match "\\.pdf\\'" buffer-file-name)
              (open-pdf-with-zathura buffer-file-name)
              (kill-buffer))))
#+END_SRC


* Treemacs Configuration
Configure Treemacs to open with the window setup.

#+BEGIN_SRC emacs-lisp :tangle yes
(add-hook 'window-setup-hook #'treemacs 'append)
#+END_SRC


* Keybindings
Customize global keybindings.

#+BEGIN_SRC emacs-lisp :tangle yes
#+END_SRC
